apiVersion: apps/v1
kind: Deployment
metadata:
  name: pimcore
spec:
  selector:
    matchLabels:
      app: pimcore
  replicas: 1
  template:
    metadata:
      labels:
        app: pimcore
    spec:
      initContainers:
        - name: pimcore-migration
          image: pimcore/pimcore:2024.x
          command: ["/var/www/html/bin/console", "pimcore:migrations:migrate", "--no-interaction"]
          envFrom:
            - configMapRef:
                name: pimcore-config
          volumeMounts:
            - name: pimcore-var-volume
              mountPath: /var/www/html/var
      containers:
        - name: pimcore
          image: pimcore/pimcore:2024.x
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: pimcore-config
          volumeMounts:
            - name: pimcore-assets-volume
              mountPath: /var/www/html/public/var/assets
            - name: pimcore-var-volume
              mountPath: /var/www/html/var
        - name: pimcore-messenger # Sidecar container
          image: pimcore/pimcore:2024.x # Use the same image
          command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
          envFrom:
            - configMapRef:
                name: pimcore-config
          volumeMounts:
            - name: pimcore-var-volume
              mountPath: /var/www/html/var
            - name: supervisord-config
              mountPath: /etc/supervisord.conf
              subPath: supervisord.conf
      volumes:
        - name: pimcore-assets-volume
          persistentVolumeClaim:
            claimName: pimcore-assets-pvc
        - name: pimcore-var-volume
          persistentVolumeClaim:
            claimName: pimcore-var-pvc
        - name: supervisord-config
          configMap:
            name: supervisord-config
